### ISSUE TITLE
Rename copy_lines to process_list_files

### ISSUE THREAD

**Issue by sladenheim** [rcs-si/project_jungle#17]
The inputs to process_list_files should be:

- input_filepath
- output_filepath

Remove num_lines as an input parameter

This function should also count the number of subdirectories/files. You can append a string value to the split_lines list that has this count. The count should be the number of / in the path. You should be able to use split_line[-1].count("/").

**Comment by ChuningShi** [comment]
Updated the feature1 branch with these updates.
